repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: django-check
        name: Django system check
        entry: python3 manage.py check
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: django-migrations-check
        name: Django migrations check
        entry: python3 manage.py makemigrations --check --dry-run
        language: system
        pass_filenames: false
        stages: [pre-commit]
