# Generated by Django 6.0.6 on 2026-07-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('franchise_admin', 'Franchise Admin'), ('org_admin', 'Organisation Admin'), ('site_manager', 'Site Manager'), ('staff', 'Staff'), ('finance', 'Finance'), ('parent', 'Parent / Guardian')], default='parent', max_length=20),
        ),
    ]
