# Generated by Django 6.0.6 on 2026-07-07 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0002_attendance_collected_by_and_more"),
        ("organisations", "0002_organisation_sibling_discount_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sport", "Sport"),
                            ("creative", "Creative"),
                            ("quiet", "Quiet / homework"),
                            ("outdoor", "Outdoor"),
                            ("food", "Food / snack"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("default_duration_minutes", models.PositiveIntegerField(default=30)),
                ("resources", models.TextField(blank=True, help_text="Equipment, room, etc.")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "anchor_date",
                    models.DateField(
                        help_text="Reference date for Week A/B alternation (usually term start)."
                    ),
                ),
                (
                    "first_week",
                    models.CharField(
                        choices=[("A", "Week A"), ("B", "Week B")], default="A", max_length=1
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "session_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes",
                        to="bookings.sessiontype",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to apply to all sites.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes",
                        to="organisations.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("single", "Single day"), ("closure", "Closure / non-running")],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "replaces_day",
                    models.BooleanField(
                        default=False,
                        help_text="For single-day events: replace the whole day instead of merging.",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_events",
                        to="programme.activity",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_events",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_events",
                        to="programme.programme",
                    ),
                ),
                (
                    "session_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_events",
                        to="bookings.sessiontype",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_events",
                        to="organisations.site",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_date", "sort_order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="WeekPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_packs",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="programme",
            name="week_a_pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programmes_as_week_a",
                to="programme.weekpack",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="week_b_pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programmes_as_week_b",
                to="programme.weekpack",
            ),
        ),
        migrations.CreateModel(
            name="WeekPackBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("label", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "is_running_period",
                    models.BooleanField(
                        default=True, help_text="Uncheck for snack, break, or handover slots."
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="week_pack_blocks",
                        to="programme.activity",
                    ),
                ),
                (
                    "week_pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="programme.weekpack",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "sort_order", "start_time"],
                "unique_together": {("week_pack", "weekday", "start_time")},
            },
        ),
    ]
