# Generated by Django 6.0.6 on 2026-07-06 10:12

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="sibling_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10"),
                help_text="Discount % when booking multiple children in one checkout",
                max_digits=5,
            ),
        ),
    ]
