# Generated by Django 6.0.6 on 2026-07-06 10:12

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="collected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collections",
                to="operations.authorisedcollector",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="collection_verified_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="late_fee_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=8),
        ),
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("walk_in", "Walk-in"),
                    ("recurring", "Recurring"),
                    ("waitlist", "Waitlist"),
                ],
                default="online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="subsidy_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="operations.subsidycode",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="fsm_eligible",
            field=models.BooleanField(default=False, verbose_name="Free school meals eligible"),
        ),
        migrations.AddField(
            model_name="child",
            name="pupil_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="session",
            name="register_closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="register_closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registers_closed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="register_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sessiontype",
            name="late_pickup_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Fee per 15 minutes after grace period",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="sessiontype",
            name="late_pickup_grace_minutes",
            field=models.PositiveIntegerField(default=15),
        ),
    ]
